use lpmf;

insert into clean_up_maps (`from`, `to`, `category`)
VALUES
("Afera Tomasza Crowna", "Afera Thomasa Crowna","movie"),
("Braveheart - waleczne serce", "Braveheart - Waleczne serce","movie"),
("Braveheart: Waleczne serce", "Braveheart - Waleczne serce","movie"),
("Casino Royal", "Casino Royale","movie"),
("Czas honoru - Czas honoru", "Czas honoru","movie"),
("Frozen", "Frozen - Kraina lodu","movie"),
("Frozen: Kraina lodu", "Frozen - Kraina lodu","movie"),
("Gwiezdne wojny - Atak Klonów", "Gwiezdne wojny - Atak Klonów","movie"),
("Gwiezdne wojny - Imperium kontratakuje", "Gwiezdne wojny - Imperium kontratakuje","movie"),
("Gwiezdne wojny. Przebudzenie mocy", "Gwiezdne wojny - Przebudzenie mocy","movie"),
("Gwiezdne wojny: Imperium kontratakuje", "Gwiezdne wojny - Imperium kontratakuje","movie"),
("Gwiezdne wojny: Ostatni Jedi", "Gwiezdne wojny - Ostatni Jedi","movie"),
("Gwiezdne wojny: Zemsta Sithów", "Gwiezdne wojny - Zemsta Sithów","movie"),
("Harry Potter i kamień filozoficzny", "Harry Potter i Kamień Filozoficzny","movie"),
("Hobbit - niezwykła podróż", "Hobbit - Niezwykła podróż","movie"),
("Hobbit: Bitwa Pięciu Armii", "Hobbit - Bitwa Pięciu Armii","movie"),
("Hobbit: Niezwykła podróż", "Hobbit - Niezwykła podróż","movie"),
("Hobbit: Pustkowie Smauga", "Hobbit - Pustkowie Smauga","movie"),
("House of Cards", "House Of Cards","movie"),
("Król lew", "Król Lew","movie"),
("Labirynt fauna", "Labirynt Fauna","movie"),
("Mandela", "Mandela - Long Walk to Freedom","movie"),
("Opowieści z Narnii", "Opowieści z Narnii - Lew, Czarownica i Stara Szafa","movie"),
("Opowieści z Narnii: Lew, czarownica i stara szafa", "Opowieści z Narnii - Lew, Czarownica i Stara Szafa","movie"),
("Opowieści z Narnii: lew, czarownica i stara szafa", "Opowieści z Narnii - Lew, Czarownica i Stara Szafa","movie"),
("Piraci z Karaibów", "Piraci z Karaibów - Klątwa Czarnej Perły","movie"),
("Piraci z Karaibów - klątwa Czarnej Perły", "Piraci z Karaibów - Klątwa Czarnej Perły","movie"),
("Piraci z Karaibów - na krańcu świata", "Piraci z Karaibów - Na krańcu świata","movie"),
("Piraci z Karaibów: Na nieznanych wodach", "Piraci z Karaibów - Na nieznanych wodach","movie"),
("Sherlock Holmes - gra cieni", "Sherlock Holmes - Gra cieni","movie"),
("Slumdog. Milioner z ulicy", "Slumdog - Milioner z ulicy","movie"),
("Slumdog: Milioner z ulicy", "Slumdog - Milioner z ulicy","movie"),
("Spirited Away", "Spirited Away - W krainie bogów","movie"),
("Spirited Away - w krainie bogów", "Spirited Away - W krainie bogów","movie"),
("Star Trek: The Motion Picture", "Star Trek","movie"),
("Titanic: Anniversary Edition", "Titanic","movie"),
("Władca Pierścieni - Drużyna Pierścienia", "Władca Pierścieni - Drużyna Pierścienia","movie"),
("Władca Pierścieni: Dwie Wieże", "Władca Pierścieni - Dwie Wieże","movie"),
("Władca Pierścieni: Powrót króla", "Władca Pierścieni - Powrót Króla","movie"),
("Władca pierścieni: Drużyna Pierścienia", "Władca Pierścieni - Drużyna Pierścienia","movie"),
("Władca pierścieni: Drużyna pierścienia", "Władca Pierścieni - Drużyna Pierścienia","movie"),
("Władca pierścieni: Dwie wieże", "Władca Pierścieni - Dwie Wieże","movie"),
("Władca pierścieni: Powrót króla", "Władca Pierścieni - Powrót Króla","movie");

insert into clean_up_maps (`from`, `to`, `category`)
VALUES
("A.R. Rahman","Allah Rakha Rahman","artist"),
("B.J. Thomas","Billy Joe Thomas","artist"),
("Giulia y los Tellarini","Giulia y Los Tellarini","artist"),
("Rodrigo & Gabriela","Rodrigo y Gabriela","artist"),
("Kelly / Reynolds / O'Connor","Gene Kelly / Donald O'Connor / Debbie Reynolds","artist"),
("Komeda/ Osiecka/ Fetting","Agnieszka Osiecka / Krzysztof Komeda / Edmund Fetting","artist"),
("Tykwer / Heil / Klimek","Reinhold Heil / Johnny Klimek / Tom Tykwer","artist"),
("G.Ragni / J.Rado / G.Mc.Dermont","Gerome Ragni / James Rado / Galt MacDermot","artist"),
("Osiecka / Komeda / Edmund Fetting","Agnieszka Osiecka / Krzysztof Komeda / Edmund Fetting","artist"),
("Alan Menken / Celine Dion&Peabo Bryson","Alan Menken / Celine Dion / Peabo Bryson","artist"),
("Hans Zimmer / Rodrigo & Gabriela","Hans Zimmer / Rodrigo y Gabriela","artist"),
("Burt Bacharach / B.J. Thomas","Burt Bacharach / Billy Joe Thomas","artist"),
("Matos Rodriguez / Maroni / Contursi","Matos Rodriguez / Pascual Contursi / Enrique Maroni","artist"),
("Jan A.P. Kaczmarek / Leszek Możdżer","Jan A. P. Kaczmarek / Leszek Możdżer","artist"),
("Django Reinhardt & Stephane Grappelli","Django Reinhardt / Stephane Grappelli","artist"),
("Jamie Cullum, Clint Eastwood","Jamie Cullum / Clint Eastwood","artist"),
("Simon & Garfunkel","Paul Simon / Art Garfunkel","artist"),
("Simon / Garfunkel","Paul Simon / Art Garfunkel","artist"),
("Jan A.P. Kaczmarek","Jan A. P. Kaczmarek","artist"),
("Heil Reinhold, Klimek Johnny & Tykwer Tom","Reinhold Heil / Johnny Klimek / Tom Tykwer","artist"),
("Reinhold / Klimek / Tykwer","Reinhold Heil / Johnny Klimek / Tom Tykwer","artist"),
("Herve Roy","Hervé Roy","artist"),
("Joe Hisaiashi","Joe Hisaishi","artist"),
("Joe Hisaishi","Joe Hisaishi","artist"),
("Randy Newman & Lyle Lovett","Randy Newman / Lyle Lovett","artist"),
("Ryuichi Sakamoto","Ryūichi Sakamoto","artist");

insert into clean_up_maps (`from`, `to`, `category`)
VALUES
("Beauty and the Beast","Beauty and The Beast","song"),
("Cops Or Criminals","Cops or Criminals","song"),
("Lillies of the valley","Lillies of the Valley","song"),
("Over The Rainbow","Over the Rainbow","song"),
("Sleep Safe And Warm","Sleep Safe and Warm","song"),
("Song of The Lonely Mountain","Song of the Lonely Mountain","song"),
("The Sound of Silence","The Sound Of Silence","song"),
("Will And Elizabeth","Will and Elizabeth","song"),
("With A Little Help From My Friends","With a Little Help From My Friends","song"),
("Young And Beautiful","Young and Beautiful","song"),
("temat","Temat","song"),
("czołówka","Czołówka","song"),
("Gabriel`s Oboe","Gabriel's Oboe","song"),
("Gabriel\\'s Oboe / Falls","Gabriel's Oboe / Falls","song"),
("suita","Suita","song"),
("Leaving Wallbrok/ On the Road","Leaving Wallbrok / On the Road","song"),
("The heart Asks Pleasure First","The Heart Asks Pleasure First","song");